### ISSUE TITLE
fw_protect error when packing metadata

### ISSUE THREAD

**Issue by randall-sim** [GandyT/FirmwareDistribution#7]
```
Traceback (most recent call last):
  File "/home/jovyan/work/FirmwareDistribution/tools/./fw_protect.py", line 93, in <module>
    protect_firmware(infile=args.infile, outfile=args.outfile, version=int(args.version), message=args.message)
  File "/home/jovyan/work/FirmwareDistribution/tools/./fw_protect.py", line 33, in protect_firmware
    metadata = struct.pack('<HHH', message.encode(), version, len(firmware))
struct.error: required argument is not an integer
```

**Comment by randall-sim** [comment]
replace message.encode() with len(message.encode())
